version: '3.9'
name: 'social_network'

# Configurations shared between api service, celery and celery beat.
x-base-api: &base-api
  env_file:
    - ../api/.env
  volumes:
    - ../api:/opt/api
  build:
    context: ..
    dockerfile: docker/images/api/Dockerfile
    target: local

services:
  api:
    <<: *base-api
    command: ["make", "run"]
    depends_on:
      - postgres-db
    ports:
      - ${LOCAL_IP:-127.0.0.1}:${API_LOCAL_PORT:-8000}:8000

  postgres-db:
    environment:
      POSTGRES_USER: social_network_user
      POSTGRES_DB: social_network_db
      POSTGRES_PASSWORD: social_network_password
    image: postgres:15.0-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data:rw

volumes:
  pg_data: {}
  redis_data: {}
  minio_data: {}


networks:
  default:
    driver: bridge
